### ISSUE TITLE
Tests fail because pysolr not listed as requirement

### ISSUE THREAD

**Issue by cthoyt** [ndexbio/ndex2-client#6]
Tests failing from missing module `pysolr`. Was using `ndex2==1.0`, but it looks like this is already added to the requirements.txt and setup.py though

```
Failure: ModuleNotFoundError (No module named 'pysolr') ... ERROR

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'pysolr')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cthoyt/dev/ndex2-client/nicecxModel/tests/test_load_network.py", line 20, in <module>
    from ndex2.NetworkQuery import NetworkQuery
  File "/Users/cthoyt/dev/ndex2-client/ndex2/NetworkQuery.py", line 6, in <module>
    import pysolr
ModuleNotFoundError: No module named 'pysolr'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'pysolr')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cthoyt/dev/ndex2-client/nicecxModel/tests/test_network_editing.py", line 26, in <module>
    from ndex2.NetworkQuery import NetworkQuery
  File "/Users/cthoyt/dev/ndex2-client/ndex2/NetworkQuery.py", line 6, in <module>
    import pysolr
ModuleNotFoundError: No module named 'pysolr'
```

**Comment by agary-ucsd** [comment]
Added pysolr to requirements.txt and setup.py
